### ISSUE TITLE
Request: customise colors

### ISSUE THREAD

**Issue by lucacr** [hartez/TodotxtTouch.WindowsPhone#24]
Absolutely love the app, use it with a Lumia 625 WP8.1 and Dropbox, and can sync from just about anywhere (work pc, iPad, ubuntu etc). It follows the todo.txt format/rules very well. My only request is the ability to customise colors, i.e. possibly for different priorities, or to set off the context or project. Right now, for example, the default (B) priority is hard to read on my phone, a dark green on a black background.

Other than that, funky little app :-)

**Comment by hartez** [comment]
@lucacr - I'm glad you like the app! I'm hoping to put out another round up updates soon, I'll try to work this one in.

**Comment by hartez** [comment]
Added in 1.7 and up

**Comment by lucacr** [comment]
woo-hoo! happy days. :-) :+1:
