### ISSUE TITLE
Cancel doesn't work when creating a new todo item

### ISSUE THREAD

**Issue by Piscean** [hartez/TodotxtTouch.WindowsPhone#8]
Click + to create a new Task.
In the Task edit page, click X to cancel.
Nothing happens.  I expect it to cancel and go back to the main screen listing all my tasks.

**Comment by hartez** [comment]
The intent of this button was to revert any changes that had been made to a task without saving it. It was confusing and didn't work all that well, so it's been removed (as of version 1.7). To cancel changes without saving, just use the back button.
